### ISSUE TITLE
h5py 2.7.1 causes test failures

### ISSUE THREAD

**Issue by bsipocz** [MacPython/astropy-wheels#7]
I have some troubles building the wheels for the new 2.0.2 release due to the same h5py error reported in the astropy core repo:

https://github.com/astropy/astropy/issues/6534

@matthew-brett - We may not even fix this issue for the core repo, and definitely not something that requires a new release to be made. I try to make a quick patch that simply skips this test here, but envision that will run into troubles, so it would very useful if you could point me to a patch example. 

And if nothing else works I suggest to skip the wheel building for python2.7 and keep only the python3 versions.

**Comment by matthew-brett** [comment]
@bsipocz - I guess you are saying that you've already tagged / uploaded source for 2.0.2?

Does pytest have an easy incantation to skip a particular test?  Could you use that in the `config.sh` test runner?

Otherwise, you can always patch the installed sources before running the tests - here's an example for matplotlib:

https://github.com/MacPython/matplotlib-wheels/blob/d49b287e683ea8b27940ab16f303f9b836788fdd/config.sh#L60

**Comment by bsipocz** [comment]
Yes, I've uploaded 2.0.2 on Friday along with the windows wheels. Travis had problems, so I was unable to see that there are problems here on travis.

**Comment by matthew-brett** [comment]
:) - yes - saw that - good old travis - we need them but they are unreliable ...

**Comment by bsipocz** [comment]
I really wish they have finally introduced a separate osx queue, avoiding everyone stuck in that gridlock.

Anyway, now I'm patching astropy and once that is merge, will move it over here. A bit of cheating, but since it only affects the test it should be OK I think.

**Comment by astrofrog** [comment]
I believe this is no longer relevant
